name: desafio_tecnico_2_escribo
description: "Estante de livros."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0
  mobx_codegen: ^2.4.0
  http: ^1.1.2
  get_it: ^7.6.4
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  vocsy_epub_viewer: ^2.0.0
  permission_handler: ^10.3.0
  dio: ^5.2.1+1
  path_provider: ^2.0.15
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

  assets:
    - assets/imagens/
